sudo: false
language: java
jdk:
- openjdk16
os:
- linux
script: mvn clean install -Pinstall-runtime
before_script:
- wget https://download-gcdn.ej-technologies.com/install4j/install4j_linux-x64_9_0_2.tar.gz
- tar zxvf install4j_linux-x64_9_0_2.tar.gz
- mvn clean
- mvn install4j:install-license
deploy:
- provider: releases
  skip_cleanup: true
  api_key:
    secure: eXWmeEqed9dok9+JZNDEHabvFObneOtmEsoiA7T4RrKGNFOnrhH/tRh47uEmLsoXddnCu56Pykv3vatmWsXqdcKevfaXz+D4Rlw+O0oxQjVtxluHCjlStzPCMwYzW5n/mIns8TnqCLyLzdcT/JkB9lhA7jPmCBlBHh+tsu4UInU=
  file:
  - "/home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_Mac.dmg"
  - "/home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_Linux.tar.gz"
  - "/home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_Windows.exe"
  - "/home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_Windows.zip"
  - "/home/travis/build/asciidocfx/AsciidocFX/target/media/updates.xml"
  on:
    tags: true
    all_branches: true
    repo: asciidocfx/AsciidocFX
- provider: s3
  skip_cleanup: true
  access_key_id: AKIAIHHVKYJLE6JUVEMA
  secret_access_key:
    secure: u3AfnEBb4o1boHzYsbPBlYqsxkKKWd4e02sabTLB7RRojgW1PpvGpvMCEZQ7EdziAfqJV2qZAI4ayYen36t2S0P9LMtt8NbnSO9RSF41Na+cGlsetbHgbejjK3QC5wM18j263gaxlM6uKD9wbO9VYaujYE6r66UUGdrQkNZh9xc=
  bucket: asciidoc-fx
  acl: public_read
  local_dir: "/home/travis/build/asciidocfx/AsciidocFX/target/media"
  file:
  - "/home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_Mac.dmg"
  - "/home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_Linux.tar.gz"
  - "/home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_Windows.exe"
  - "/home/travis/build/asciidocfx/AsciidocFX/target/media/AsciidocFX_Windows.zip"
  - "/home/travis/build/asciidocfx/AsciidocFX/target/media/updates.xml"
  on:
    tags: true
    all_branches: true
    repo: asciidocfx/AsciidocFX
env:
  global:
  - secure: x4NoL51Uq5eGy+qYR3R5ca5J16lXN+45EwcRTE3FBxzxN91vK6GrKW8sbjZLTXeEIjhn9X1IEe8A2ljh4fnkOtIGl2bVHm8KJPNWa/EKmCLZ7KjCzXtyI5743pb+IJpIyCaevwasTBGFvsrs3NOsV/zipk0nEu08VdqEvp7AsXE=
  - secure: xfIJj1AUhUgXfrMZStwGv0njAc8eSPe38M+QOyApgl1LriEc2WX0vdf/zQhcELHmuAidkDV6t4KCQ6IavzylvYHbrSL3Ki7uTIf1qWKPkJKJq0yhOON4Qw44sziM9ePAMLu09C6sOzXkcIYw8VJGQA4Dh8OxiKUePX0wqUw9zIY=
  - secure: itDqULG69MoCnvLvMoFpBC8osAb/603jmc47hwC3qn1X+egKrT8kM/w8DC5fYgwp45LKBaxZhxY1q2twxvC6tW28/Zc31kR65RkfbRv5b2jqvb+PFtBSTvBDtKQxPf5DgK1yvqZYZ8r46uYEjepKwELhsYF05W+4irZqakd3aIo=
  - secure: xm/y8T8BYyTxr6qRJ6UP/GkMCEcPDAdrlMysOeZ4XChwZOGU4n0ECkxz0c9xtbdmAkgISYAhHTckQNHQiuOV1AGp+EZMvapPoT3k+AR3bv20NDb9xlTz2p3LPSmH35mRjttHslj2FE+4k+V5H8BoQIMtdkcFUye+PWn2hk54kZg=
  - secure: aVp+h5KCEPp28y/RHiUVe+/Gyt52QNOXVJNAM0Y/GJ8M4ReJVC/INofHysPbIw/DDkTJXvwe19NT64bkpvwMJT69yvdx2vhNN8hWAxBZ7JS0WG92At3Jm0KUT2aX0zBHZEEf9PIpB9jPzUyS1CjILUmuSHL1UXTtivsEEi3jtgQ=
  - secure: nKCOCCe3kR4es1qYdYawvdYMerrXcXqN9XtWbxGCjWte0tIwnvdMI+WlOzNoe03oqso/YHdkB/LekcCDPY//tAQd9kYD7kfO7ZNvwCkhf0ERKs5QGuLBk6XvDz2Rmx+CRCBxmfMKe+dkCgPNcRTSFtSURoXnbyUCI0lTAyO6Evs=
before_install:
- openssl aes-256-cbc -K $encrypted_56a53bf9cdec_key -iv $encrypted_56a53bf9cdec_iv
  -in code_sign.p12.enc -out code_sign.p12 -d
